sudo: required
services:
    - docker

before_install:
    - docker build   -t jonbelinfante/docker-multi-container3 -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true -t jonbelinfante/docker-multi-container3 npm run test


